# Generated by Django 5.2.9 on 2025-12-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_bible', models.TextField(verbose_name='Цитата из Библии')),
                ('text_about', models.TextField(verbose_name='Текст О нас')),
                ('text_footer', models.CharField(max_length=200, verbose_name='Текст в футере')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date_saturday', models.CharField(max_length=50, verbose_name='Время Суббота')),
                ('date_sunday', models.CharField(max_length=50, verbose_name='Время Воскресенье')),
            ],
        ),
    ]
