# Generated by Django 5.1.7 on 2025-12-17 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_bible', models.TextField(blank=True, default='Заголовок', verbose_name='Заголовок')),
                ('text_bible', models.TextField(blank=True, default='Текст', verbose_name='Текст')),
                ('text_adres', models.CharField(blank=True, default='Адрес', max_length=50, verbose_name='Адрес')),
                ('text_adres_link', models.CharField(blank=True, default='Адрес_ccилка', max_length=200, verbose_name='Адрес_ccилка')),
                ('phone', models.CharField(blank=True, default='+000000000', max_length=20, verbose_name='Телефон')),
                ('about_us_text1', models.TextField(blank=True, default='Текст', verbose_name='Первый абзац')),
                ('about_us_text2', models.TextField(blank=True, default='Текст', verbose_name='Второй абзац')),
                ('text_email', models.EmailField(blank=True, default='example@email.com', max_length=254)),
                ('meting_saturday', models.CharField(blank=True, default='10:00', max_length=50, verbose_name='Суббота')),
                ('meting_sanday', models.CharField(blank=True, default='10:00', max_length=50, verbose_name='Воскресенье')),
                ('is_reg_open', models.BooleanField(default=False, verbose_name='Регестрация открыта')),
                ('text_register', models.TextField(blank=True, verbose_name='Текст для регистрации')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('user_phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('age', models.PositiveSmallIntegerField(verbose_name='Возраст')),
                ('text_comment', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
